<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>6 страничка</title>
    <link rel="stylesheet" href="./css/6.css">
</head>
<body>
    <div class="main_bg">
        <div class="main_wrapper">
            <div class="main_info">
              <div class="zan">
                <b class="text_zan">Занятие</b>
              </div>
              <div class="pred">
                <b class="text_pred">Математический анализ</b>
              </div>
                <div class="Tab">
                  <input class="input-text_1" rows="4" cols="50" placeholder="Дата">
                  <input class="input-text_3" rows="4" cols="50" placeholder="Начало">
                  <input class="input-text_4" rows="4" cols="50" placeholder="Конец">
                  <input class="input-text_5" rows="4" cols="50" placeholder="Продолжительность">
                  <input class="input-text_6" rows="4" cols="50" placeholder="Аудитория">
                  <div class="input-text_7">
                    <div class="input-text_7_1">
                      <b class="text_1_1">Экзамен был тяжёлым</b>
                      <div class="input-text_8">
                        <b class="input-text_2_1">Олег</b>
                      </div>
                    </div>
                    <!-- <div class="pan_1">
                      <button class="text_3">Получить оповещение</button>
                    </div>  -->
                  </div>
                <div>
                  <button class="note_button_1">Отправить</button>
                </div>
                <div>
                  <button class="pan_1">Получить оповещение</button>
                </div>
                <input class="input" placeholder="Введите комментарий">
                </div>
            </div>

            <div class="note_wrapper">
                <div class="note_inp">
                    <div class="note_title">
                        <div class="main_block main_block__title">Заметка</div>
                    </div>
                    <div class="note_container">
                        <textarea placeholder="Заметка..." class="note_input"></textarea>
                    </div>
                    <button class="note_button">Отправить</button>
                    
                </div>
            </div>
        </div>
    </div>
    
</body>
</html>