<!DOCTYPE html>
<html>
<#import "spring.ftl" as spring />
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="initial-scale=1, width=device-width" />
  <link rel="stylesheet" type="text/css"
        href="<@spring.url '/public/desktop-head.css'/>"/>
</head>
<body>
  <div class="des-1">
    <div class="tb_1">
      <a class="a_1" href="#">Календарь</a>
      <a class="a_2" href="#">Уведомления</a>
      <a class="a_3" href="./desktop-3.html">Добавить предмет</a>
      <a class="a_4" href="#">Личный кабинет</a>
      <b class="ras2p">Расписание на каждый день</b>
      
    </div>
  </div>  
  <div class="bg"></div>
  <div class="bg bg2"></div>
  <div class="bg bg3"></div>
</body>
</html>
